feat(CI-CD): тестирование работы простого ci_22

diff --git a/.github/workflows/first-check.yml b/.github/workflows/first-check.yml
--- a/.github/workflows/first-check.yml
+++ b/.github/workflows/first-check.yml
@@ -50,13 +50,13 @@ jobs:
         run:
           mvn spring-boot:run -Dserver.port=8080 &
 
-#      - name: Проверка статуса Spring Boot приложения
-#        run: |
-#          status=$?
-#          if [ $status -ne 0 ]; then
-#          echo "Spring Boot application failed to start with status $status";
-#          exit 1;
-#          fi
+      - name: Проверка статуса Spring Boot приложения
+        run: |
+          status=$?
+          if [ $status -ne 0 ]; then
+          echo "Spring Boot application failed to start with status $status";
+          exit 1;
+          fi
 
       #- name: Проход Postman тестов с baseUrl http://localhost:8080
       #  run: npx newman run ./postman/filmorate.json --env-var baseUrl=http://localhost:8080
