feat(CI-CD): тестирование работы простого ci_11

diff --git a/.github/workflows/first-check.yml b/.github/workflows/first-check.yml
--- a/.github/workflows/first-check.yml
+++ b/.github/workflows/first-check.yml
@@ -48,8 +48,15 @@ jobs:
 
       - name: Запуск приложения на порту 8080
         run:
-          set -e
           mvn spring-boot:run -Dserver.port=8080
+
+      - name: Check Spring Boot application status
+        run: |
+          status=$?
+          if [ $status -ne 0 ]; then
+          echo "Spring Boot application failed to start with status $status";
+          exit 1;
+          fi
 
       #- name: Проход Postman тестов с baseUrl http://localhost:8080
       #  run: npx newman run ./postman/filmorate.json --env-var baseUrl=http://localhost:8080
